language: node_js
node_js:
  - 12
before_deploy:
  - curl https://github.com/lindell/github-release-cli/releases/download/1.1.0/github-releaser-travis -L --output github-releaser && chmod +x github-releaser
  - export BODY=$(node ./.fetch_lastest_commits.js)
deploy:
  provider: script
  script: ./github-releaser -draft -verbose
  skip_cleanup: true
  on:
    tags: true
    condition: '$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$'
