language: node_js
node_js:
  - 12
before_deploy:
  - "export CHANGELOG_BODY=$(node ./.fetch_lastest_commits.js)"
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  skip_cleanup: true
  body: ${CHANGELOG_BODY}
  on:
    tags: true
    condition: '$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$'
